### ISSUE TITLE
Exchange tablets and alchemy pedestals allow taking items from them during crafting

### ISSUE THREAD

**Issue by slava110** [RCXcrafter/EmbersRekindled#31]
Exchange tablets and alchemy pedestals allow taking items from them during crafting and don't stop the recipe. If you take all ingredients - it will crash and break world (unable to load it again)
![2024-04-14_12 09 15](https://github.com/RCXcrafter/EmbersRekindled/assets/26705162/3c0b71b6-7251-475e-bb6d-08b5d99df613)
Crash error:
```
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:322) ~[?:?] {}
	at com.rekindled.embers.blockentity.AlchemyTabletBlockEntity.clientTick(AlchemyTabletBlockEntity.java:179) ~[embersrekindled-1.20.1-1.1.1.jar%23352!/:1.20.1-1.1.1] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468)
```

**Comment by RCXcrafter** [comment]
Fixed in version 1.2.0
