### ISSUE TITLE
Compatibility Issue between Embers and Create

### ISSUE THREAD

**Issue by ponpippi** [RCXcrafter/EmbersRekindled#50]
I want to extend my heartfelt gratitude for making Embers playable on Minecraft 1.20.1. It has brought so much joy to my gameplay experience—thank you!

However, I’ve encountered an issue when placing the Mechanical Core from Embers on an Ember Bore and then attaching a Funnel from the Create mod. Attempting to break the Funnel in this setup causes the game to crash. If this issue is occurring due to something on Create's side and is beyond what can be addressed in Embers, I apologize for bringing it up here.

Below is the crash report for your reference:

```
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraftforge.common.util.LazyOptional.removeListener(net.minecraftforge.common.util.NonNullConsumer)'
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.CapManipulationBehaviourBase.removeListener(CapManipulationBehaviourBase.java:84) ~[create-1.20.1-0.5.1.i.jar%23160!/:0.5.1.i] {re:classloading}
	at com.simibubi.create.content.logistics.funnel.FunnelBlockEntity.invalidateCaps(FunnelBlockEntity.java:278) ~[create-1.20.1-0.5.1.i.jar%23160!/:0.5.1.i] {re:classloading}
	at net.minecraft.world.level.block.entity.BlockEntity.m_7651_(BlockEntity.java:173) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceRemoveMixin,pl:mixin:A}
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.m_7651_(SmartBlockEntity.java:132) ~[create-1.20.1-0.5.1.i.jar%23160!/:0.5.1.i] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_8114_(LevelChunk.java:404) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:159) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:196) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.common.extensions.IForgeBlock.onDestroyedByPlayer(IForgeBlock.java:195) ~[forge-1.20.1-47.1.106-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.extensions.IForgeBlockState.onDestroyedByPlayer(IForgeBlockState.java:129) ~[forge-1.20.1-47.1.106-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105267_(MultiPlayerGameMode.java:123) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233754_(MultiPlayerGameMode.java:145) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105269_(MultiPlayerGameMode.java:143) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1632) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1972) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.1.106.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

		forge-1.20.1-47.1.106-universal.jar               |NeoForge                      |forge                         |47.1.106            |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.11-13.jar               |Flywheel                      |flywheel                      |0.6.11-13           |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.i.jar                         |Create                        |create                        |0.5.1.i             |DONE      |Manifest: NOSIGNATURE
		embersrekindled-1.20.1-1.3.9.jar                  |Embers Rekindled              |embers                        |1.20.1-1.3.9        |DONE      |Manifest: NOSIGNATURE
		
I hope this feedback is helpful, and I would love to see both mods working seamlessly together. Thank you again for all the hard work you put into these mods!

**Comment by VoidLeech** [comment]
You should switch to Forge (47.1.43 or later) as Neoforge is unmaintained for 1.20.1 (and in this case, is missing a method that Create needs)
